fix qvm-run optional args, fix template selection

diff --git a/qubes-update-all b/qubes-update-all
--- a/qubes-update-all
+++ b/qubes-update-all
@@ -18,7 +18,8 @@ Options:
 
 --autoclean, -ac  = autoclean
 --autoremove, -ar = autoremove
---help, -h        = help menu"
+--help, -h        = help menu
+"
     exit 0
     ;;
     *)
@@ -33,8 +34,8 @@ updatevm="gateway-update"
 
 ## Log output dir and file.
 ## If left empty a dir and file will be created in current dir.
-logdir="${HOME}/update-all-templates-log/"
-logfile="${HOME}/update-all-templates-log/update-all-templates.log"
+logdir=
+logfile=
 
 ## Set variables if empty.
 if [[ -z "${updatevm}" ]]; then
@@ -46,7 +47,7 @@ if [[ -z "${logdir}" ]]; then
 fi
 
 if [[ -z "${logfile}" ]]; then
-  logfile="${logdir}update-all-templates.log"
+  logfile="${logdir}"update-all-templates.log
 fi
 
 if [[ ! -e "${logdir}"  ]]; then
@@ -64,14 +65,14 @@ fi
 ## Print enabled options.
 clear
 if [[ "${autoremove}" -eq "1" ]]; then
-  printf "[+] AUTOREMOVE ENABLED\n"
+  printf "+ AUTOREMOVE ENABLED\n"
 fi
 if [[ "${autoclean}" -eq "1" ]]; then
-  printf "[+] AUTOCLEAN ENABLED\n"
+  printf "+ AUTOCLEAN ENABLED\n"
 fi
 
 ## Start update VM, wait for Tor.
-printf "[+] Starting update VM. Waiting for Tor to connect...\n\n"
+printf "\nStarting update VM and waiting for Tor to connect...\n\n"
 if [[ $(qvm-ls --raw-data -O state "${updatevm}" | grep -c "Running") -ne "1" ]]; then
   updatevm_was_running="0"
 else
@@ -100,7 +101,7 @@ while [[ $(qvm-run -u user -p "${updatevm}" 'grep "$(date -u +%b\ %d)" /var/log/
 done
 
 ## Upgrade Debian based TemplateVM's.
-for vm in $(qvm-ls --fields name,netvm --raw-data --tags debian | grep "gateway-" | cut -d "|" -f 1 | sort); do
+for vm in $(qvm-ls --fields name,netvm --raw-data --tags debian whonix-updatevm | grep "gateway-" | cut -d "|" -f 1 | sort); do
   printf "\n[+] Starting upgrade for VM "${vm}" at $(date +%x-%T).\n\n" | tee -a "${logfile}"
   ## Check if vm was running.
   if [[ $(qvm-ls --raw-data -O state "${vm}" | grep -c "Running") -ne "1" ]]; then
@@ -110,35 +111,35 @@ for vm in $(qvm-ls --fields name,netvm --raw-data --tags debian | grep "gateway-
   fi
   ## Start vm, wait for it.
   qvm-start -q --skip-if-running "${vm}"
-  while [[ $(qvm-ls --fields name,state,class --raw-data --tags debian | grep "${vm}" | grep -c "Running") -ne "1" ]]; do
+  while [[ $(qvm-ls --fields name,state,class --raw-data --tags debian whonix-updatevm | grep "${vm}" | grep -c "Running") -ne "1" ]]; do
     sleep 1
   done
   ## Start apt update. Give 10 retries.
   aborted_update="0"
   update_count="0"
-  qvm-run -q --nogui -p "${vm}" 'export DEBIAN_FRONTEND="noninteractive"; export TERM="vt100"; sudo timeout 10m sudo apt update; printf "Exit code: $?\n"' | tee -a "${logfile}"
+  qvm-run --nogui -p -q -u root "${vm}" 'export DEBIAN_FRONTEND="noninteractive" TERM="vt100"; timeout 10m sudo apt update; printf "Exit code: $?\n"' | tee -a "${logfile}"
   while [[ $(tail -1 "${logfile}" | sed 's|Exit\ code\:\ ||') -ne "0" ]] ; do
     update_count=$((update_count+1))
-    printf "\n[!][!] UPDATE FAILED FOR: "${vm}". RETRY ATTEMPT "${update_count}" / 10. [!][!]\n\n" | tee -a "${logfile}"
+    printf "\n[!][!] UPDATE FAILED FOR: "${vm}". RETRY ATTEMPT $update_count / 10. [!][!]\n\n" | tee -a "${logfile}"
     sleep 10
-    qvm-run -q --nogui -p "${vm}" 'export DEBIAN_FRONTEND="noninteractive"; export TERM="vt100"; sudo timeout 10m sudo apt update; printf "Exit code: $?\n"' | tee -a "${logfile}"
-    if [[ "${update_count}" -ge "10" ]]; then
+    qvm-run --nogui -p -q -u root "${vm}" 'export DEBIAN_FRONTEND="noninteractive" TERM="vt100"; timeout 10m sudo apt update; printf "Exit code: $?\n"' | tee -a "${logfile}"
+    if [[ "$update_count" -ge "10" ]]; then
       printf "\n[!][!] UPDATE FOR VM: "${vm}" WAS NOT SUCCESSFUL AFTER 10 RETRY ATTEMPTS. ABORTING. [!][!]\n\n" | tee -a "${logfile}"
       aborted_update="1"
       break
     fi
   done
   ## Start apt dist-upgrade if update was successful. Give 10 retries.
-  if [[ "${aborted_update}" -eq "0" ]]; then
+  if [[ "$aborted_update" -eq "0" ]]; then
     aborted_upgrade="0"
     upgrade_count="0"
-    qvm-run -q --nogui -p "${vm}" 'export DEBIAN_FRONTEND="noninteractive"; export TERM="vt100"; sudo apt dist-upgrade -V -y -q -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"; printf "Exit code: $?\n"' | tee -a "${logfile}"
+    qvm-run --nogui -p -q -u root "${vm}" 'export DEBIAN_FRONTEND="noninteractive" TERM="vt100"; apt dist-upgrade -V -y -q -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"; printf "Exit code: $?\n"' | tee -a "${logfile}"
     while [[ $(tail -1 "${logfile}" | sed 's|Exit\ code\:\ ||') -ne "0" ]]; do
       upgrade_count=$((upgrade_count+1))
       printf "\n[!][!] UPGRADE FAILED FOR VM: "${vm}". RETRY ATTEMPT "${upgrade_count}" / 10. [!][!]\n\n" | tee -a "${logfile}"
-      sleep 10
-      qvm-run -q --nogui -p "${vm}" 'export DEBIAN_FRONTEND="noninteractive"; export TERM="vt100"; sudo apt dist-upgrade -V -y -q -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"; printf "Exit code: $?\n"' | tee -a "${logfile}"
-      if [[ "${upgrade_count}" -ge "10" ]]; then
+      sleep 5
+      qvm-run --nogui -p -q -u root "${vm}" 'export DEBIAN_FRONTEND="noninteractive" TERM="vt100"; apt dist-upgrade -V -y -q -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"; printf "Exit code: $?\n"' | tee -a "${logfile}"
+      if [[ "$upgrade_count" -ge "10" ]]; then
         printf "\n[!][!] UPGRADE FOR VM: "${vm}" WAS NOT SUCCESSFUL AFTER 10 RETRY ATTEMPTS. ABORTING. [!][!]\n\n" | tee -a "${logfile}"
         aborted_upgrade="1"
         break
@@ -148,12 +149,12 @@ for vm in $(qvm-ls --fields name,netvm --raw-data --tags debian | grep "gateway-
   ## Start autoremove. Should only need one try, but we give 10 retries.
   if [[ "${aborted_update}" -eq "0" && "${aborted_upgrade}" -eq "0" && "${autoremove}" -eq "1" ]]; then
     autoremove_count="0"
-    qvm-run -q --nogui -u root -p "${vm}" 'export DEBIAN_FRONTEND="noninteractive"; export TERM="vt100"; apt autoremove -y; printf "Exit code: $?\n"' | tee -a "${logfile}"
+    qvm-run --nogui -p -q -u root "${vm}" 'export DEBIAN_FRONTEND="noninteractive" TERM="vt100"; apt autoremove -y; printf "Exit code: $?\n"' | tee -a "${logfile}"
     while [[ $(tail -1 "${logfile}" | sed 's|Exit\ code\:\ ||') -ne "0" ]]; do
       autoremove_count=$((autoremove_count+1))
       sleep 10
-      qvm-run -q --nogui -u root -p "${vm}" 'export DEBIAN_FRONTEND="noninteractive"; export TERM="vt100"; apt autoremove -y; printf "Exit code: $?\n"' | tee -a "${logfile}"
-      if [[ "${autoremove_count}" -ge "10" ]]; then
+      qvm-run --nogui -p -q -u root "${vm}" 'export DEBIAN_FRONTEND="noninteractive" TERM="vt100"; apt autoremove -y; printf "Exit code: $?\n"' | tee -a "${logfile}"
+      if [[ "$autoremove_count" -ge "10" ]]; then
         printf "\n[!][!] AUTOREMOVE FOR VM: "${vm}" WAS NOT SUCCESSFUL AFTER RETRY 10 ATTEMPTS. ABORTING. [!][!]\n\n" | tee -a "${logfile}"
         break
       fi
@@ -162,11 +163,11 @@ for vm in $(qvm-ls --fields name,netvm --raw-data --tags debian | grep "gateway-
   ## Start autoclean. Should only need one try, but we give 10 retries.
   if [[ "${aborted_update}" -eq "0" && "${aborted_upgrade}" -eq "0" && "${autoclean}" -eq "1" ]]; then
     autoclean_count="0"
-    qvm-run -q --nogui -u root -p "${vm}" 'export DEBIAN_FRONTEND=noninteractive; export TERM="vt100"; apt autoclean -y; printf "Exit code: $?\n"' | tee -a "${logfile}"
+    qvm-run --nogui -p -q -u root "${vm}" 'export DEBIAN_FRONTEND=noninteractive TERM="vt100"; apt autoclean -y; printf "Exit code: $?\n"' | tee -a "${logfile}"
     while [[ $(tail -1 "${logfile}" | sed 's|Exit\ code\:\ ||') != "0" ]]; do
       autoclean_count=$((autoremove_count+1))
       sleep 10
-      qvm-run -q --nogui -u root -p "${vm}" 'export DEBIAN_FRONTEND="noninteractive"; export TERM="vt100"; apt autoclean -y; printf "Exit code: $?\n"' | tee -a "${logfile}"
+      qvm-run --nogui -p -q -u root "${vm}" 'export DEBIAN_FRONTEND="noninteractive" TERM="vt100"; apt autoclean -y; printf "Exit code: $?\n"' | tee -a "${logfile}"
       if [[ "${autoclean_count}" -ge "10" ]]; then
         printf "\n[!][!] AUTOCLEAN FOR VM: "${vm}" WAS NOT SUCCESSFUL AFTER RETRY 10 ATTEMPTS. ABORTING. [!][!]\n\n" | tee -a "${logfile}"
         break
@@ -181,7 +182,7 @@ for vm in $(qvm-ls --fields name,netvm --raw-data --tags debian | grep "gateway-
     sleep 2s
     qvm-start "${vm}"
   fi
-  printf "\n[+] Finished upgrade for VM "${vm}" at $(date +%x-%T).\n\n" | tee -a "${logfile}"
+  printf "\n[-] Finished upgrade for VM "${vm}" at $(date +%x-%T).\n\n" | tee -a "${logfile}"
 done
 
 ## Upgrade Fedora based TemplateVM's.
@@ -199,12 +200,12 @@ for vm in $(qvm-ls --fields name,netvm --raw-data --tags fedora | grep "gateway-
     sleep 1
   done
   upgrade_count="0"
-  qvm-run -q --nogui -u root -p "${vm}" 'export TERM="vt100"; dnf upgrade --allowerasing --best --enablerepo=qubes-vm-r4.0-current-testing --refresh -v -y; printf "Exit code: $?\n"' | tee -a "${logfile}"
+  qvm-run --nogui -p -q -u root "${vm}" 'export TERM="vt100"; dnf upgrade --allowerasing --best --enablerepo=qubes-vm-r4.0-current-testing --refresh -v -y; printf "Exit code: $?\n"' | tee -a "${logfile}"
   while [[ $(tail -1 "${logfile}" | sed 's|Exit\ code\:\ ||') != "0" && $(tail -1 "${logfile}" | sed 's|Exit\ code\:\ ||') != "Complete!" ]]; do
     upgrade_count=$((upgrade_count+1))
     printf "\n[!][!] UPGRADE FAILED FOR VM: "${vm}". RETRY ATTEMPT "${upgrade_count}" / 10. [!][!]\n\n" | tee -a "${logfile}"
     sleep 10
-    qvm-run -q --nogui -u root -p "${vm}" 'export TERM="vt100"; dnf upgrade --allowerasing --best --enablerepo=qubes-vm-r4.0-current-testing  --refresh -v -y' | tee -a "${logfile}"
+    qvm-run --nogui -p -q -u root "${vm}" 'export TERM="vt100"; dnf upgrade --allowerasing --best --enablerepo=qubes-vm-r4.0-current-testing  --refresh -v -y' | tee -a "${logfile}"
     if [[ "${upgrade_count}" -ge "10" ]]; then
       printf "\n[!][!] UPGRADE FOR VM: "${vm}" WAS NOT SUCCESSFUL AFTER 10 ATTEMPTS. ABORTING. [!][!]\n\n" | tee -a "${logfile}"
       break
@@ -218,7 +219,7 @@ for vm in $(qvm-ls --fields name,netvm --raw-data --tags fedora | grep "gateway-
     sleep 2s
     qvm-start "${vm}"
   fi
-  printf "\n[+] Finished upgrade for VM "${vm}" at $(date +%x-%T).\n\n" | tee -a "${logfile}"
+  printf "\n[-] Finished upgrade for VM ${vm} at $(date +%x-%T).\n\n" | tee -a "${logfile}"
 done
 
 # Dom0 upgrade.
@@ -235,7 +236,7 @@ while [[ "${?}" -ne "0" && $(tail -5 "${logfile}" | grep -c "Nothing to download
   fi
 done
 set +o pipefail
-printf "\n[+] Finished upgrade for dom0 at $(date +%x-%T).\n\n" | tee -a "${logfile}"
+printf "\n[-] Finished upgrade for dom0 at $(date +%x-%T).\n\n" | tee -a "${logfile}"
 
 # Shutdown update vms.
 if [[ "${updatevm_was_running}" -eq "0" ]]; then
